export const INPUT_TEXT = "INPUT_TEXT"
export const SAVE_SAMPLE = "SAVE_SAMPLE"
export const ADD_WINDOW = "ADD_WINDOW"
export const CHANGE_WINDOW = "CHANGE_WINDOW"
export const GET_MIX = "GET_MIX"
export const LOAD_SAMPLE = "LOAD_SAMPLE"